---
# handlers file for Basic
- name: RestartServer
  reboot:

- name: "Atualização do repositorio do Ubuntu"
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600
  when: ansible_facts['os_family'] == "Debian"